// utils/fontAwesome.ts - Updated with missing icons
import { library } from '@fortawesome/fontawesome-svg-core'
import { 
  faLeaf,
  faUtensils,
  faPizzaSlice,
  faBowlFood,
  faHamburger,
  faBurger,
  faCoffee,
  faFish,
  faSun,
  faCheckCircle,
  faSeedling,
  faBan,
  faWineGlass,
  faCocktail,
  faBeer,
  faCalendar,
  faMusic,
  faDog,
  faUsers,
  faChild,
  faTv,
  faWheelchair,
  faParking,
  faWifi,
  faShoppingBag,
  faTruck,
  faCompass,
  faUser,
  faDollarSign,
  faMoneyBillWave,
  faGlobeAfrica,
  faCircle,
  faBreadSlice,
  faEggFried,
  faFire,
  faIceCream,
  faBars,
  faChevronLeft,
  faTimes,
  faCheck,
  faCog,
  faSearch,
  faFilter,
  faSort,
  faShare,
  faEllipsisH,
  // Additional icons needed for features
  faGlobe,
  faCross,
  faStar,
  faTree,
  faHome,
  faPlateUtensils,
  faMoon,
  faCarrot,
  faShield,
  faMapMarkerAlt,
  faPeopleGroup,
  faFamilyPants,
  faDogLeashed,
  faSandwich,
  faWheelchairMove,
  faMugHot,
  faCupcake,
  faForkKnife,
  faChopsticks,
  faSushiRoll,
  faCroissant,
  faPepperHot,
  faOlive,
  faTaco,
  faBowlChopsticksNoodles,
  faBowlHot,
  faOliveBranch,
  faShrimp,
  faDrumstickBite,
  faCow,
  faBowlSpoon,
  faSushi,
  faBurgerFries,
  faSunrise,
  faCloudMoon,
  faShishKebab,
  faCoffeePot,
  faStarOfDavid,
  faCircleGf,
  faStarAndCrescent,
  faTablePicnic,
  faUserGroup
} from '@fortawesome/pro-solid-svg-icons'

import { 
  faHeart 
} from '@fortawesome/pro-regular-svg-icons'

import { IconPrefix, IconName } from '@fortawesome/fontawesome-svg-core'

// Add all icons to the library BEFORE using them
library.add(
  // Solid icons
  faLeaf,
  faUtensils,
  faPizzaSlice,
  faBowlFood,
  faHamburger,
  faBurger,
  faCoffee,
  faFish,
  faSun,
  faCheckCircle,
  faSeedling,
  faBan,
  faWineGlass,
  faCocktail,
  faBeer,
  faCalendar,
  faEggFried,
  faMusic,
  faSandwich,
  faDog,
  faUsers,
  faChild,
  faTv,
  faWheelchair,
  faPlateUtensils,
  faParking,
  faWifi,
  faShoppingBag,
  faTruck,
  faCompass,
  faUser,
  faDollarSign,
  faMoneyBillWave,
  faGlobeAfrica,
  faCircle,
  faBreadSlice,
  faFire,
  faIceCream,
  faBars,
  faChevronLeft,
  faTimes,
  faCheck,
  faCog,
  faSearch,
  faFilter,
  faSort,
  faMugHot,
  faShare,
  faEllipsisH,
  faGlobe,
  faCross,
  faStar,
  faTree,
  faHome,
  faMoon,
  faCarrot,
  faShield,
  faMapMarkerAlt,
  faPeopleGroup,
  faFamilyPants,
  faDogLeashed,
  faWheelchairMove,
  faCupcake,
  faForkKnife,
  faChopsticks,
  faSushiRoll,
  faCroissant,
  faPepperHot,
  faOlive,
  faTaco,
  faBowlChopsticksNoodles,
  faBowlHot,
  faOliveBranch,
  faShrimp,
  faCow,
  faBowlSpoon,
  faHeart,
  faDrumstickBite,
  faSushi,
  faBurgerFries,
  faSunrise,
  faCloudMoon,
  faShishKebab,
  faCoffeePot,
  faStarOfDavid,
  faCircleGf,
  faStarAndCrescent,
  faTablePicnic,
  faUserGroup
)

// Icon style constants
export const IconStyles = {
  SOLID: 'fas' as IconPrefix,
  REGULAR: 'far' as IconPrefix,
  DUOTONE: 'fad' as IconPrefix,
  BRANDS: 'fab' as IconPrefix
} as const

// Helper function to create FontAwesome icon arrays with proper typing
export const createIcon = (style: IconPrefix, name: string): [IconPrefix, IconName] => {
  return [style, name as IconName]
}

// App icons with ONLY icons that are imported above
export const AppIcons = {
  // Navigation & System
  MENU: createIcon(IconStyles.SOLID, 'bars'),
  BACK: createIcon(IconStyles.SOLID, 'chevron-left'),
  CLOSE: createIcon(IconStyles.SOLID, 'times'),
  CHECK: createIcon(IconStyles.SOLID, 'check'),
  SETTINGS: createIcon(IconStyles.SOLID, 'cog'),
  SEARCH: createIcon(IconStyles.SOLID, 'search'),
  FILTER: createIcon(IconStyles.SOLID, 'filter'),
  SORT: createIcon(IconStyles.SOLID, 'sort'),
  HEART: createIcon(IconStyles.REGULAR, 'heart'),
  SHARE: createIcon(IconStyles.SOLID, 'share'),
  MORE: createIcon(IconStyles.SOLID, 'ellipsis-h'),

  // Meal Types
  BREAKFAST: createIcon(IconStyles.SOLID, 'sunrise'),
  LUNCH: createIcon(IconStyles.SOLID, 'sun'),
  DINNER: createIcon(IconStyles.SOLID, 'cloud-moon'),
  UTENSILS: createIcon(IconStyles.SOLID, 'utensils'), // Added for FilterModal
  COFFEE: createIcon(IconStyles.SOLID, 'coffee-pot'),
  DESSERT: createIcon(IconStyles.SOLID, 'cupcake'),

  // Budget
  DOLLAR: createIcon(IconStyles.SOLID, 'dollar-sign'),
  MONEY: createIcon(IconStyles.SOLID, 'money-bill-wave'),

  // Cuisine Types - using available icons
  AFRICAN: createIcon(IconStyles.SOLID, 'globe-africa'),
  AMERICAN: createIcon(IconStyles.SOLID, 'hamburger'),
  BAGEL: createIcon(IconStyles.SOLID, 'circle'),
  BAKERY: createIcon(IconStyles.SOLID, 'bread-slice'),
  BAR_GRILL: createIcon(IconStyles.SOLID, 'beer'),
  BBQ: createIcon(IconStyles.SOLID, 'fire'),
  BREAKFAST_FOOD: createIcon(IconStyles.SOLID, 'sun'),
  BRITISH: createIcon(IconStyles.SOLID, 'mug-hot'),
  BRAZILIAN: createIcon(IconStyles.SOLID, 'cow'),
  BRUNCH: createIcon(IconStyles.SOLID, 'coffee'),
  BURGER: createIcon(IconStyles.SOLID, 'burger'),
  CHINESE: createIcon(IconStyles.SOLID, 'chopsticks'),
  ETHIOPIAN: createIcon(IconStyles.SOLID, 'bowl-spoon'),
  FAST_FOOD: createIcon(IconStyles.SOLID, 'burger-fries'),
  FRENCH: createIcon(IconStyles.SOLID, 'croissant'),
  GERMAN: createIcon(IconStyles.SOLID, 'beer'),
  GREEK: createIcon(IconStyles.SOLID, 'olive-branch'),
  INDIAN: createIcon(IconStyles.SOLID, 'bowl-food'),
  ITALIAN: createIcon(IconStyles.SOLID, 'pizza-slice'),
  JAPANESE: createIcon(IconStyles.SOLID, 'sushi-roll'),
  KOREAN: createIcon(IconStyles.SOLID, 'bowl-chopsticks-noodles'),
  LEBANESE: createIcon(IconStyles.SOLID, 'seedling'),
  MEDITERRANEAN: createIcon(IconStyles.SOLID, 'olive'),
  MEXICAN: createIcon(IconStyles.SOLID, 'taco'),
  MIDDLE_EASTERN: createIcon(IconStyles.SOLID, 'utensils'),
  PIZZA: createIcon(IconStyles.SOLID, 'pizza-slice'),
  SANDWICH: createIcon(IconStyles.SOLID, 'sandwich'),
  SEAFOOD: createIcon(IconStyles.SOLID, 'fish'),
  SPANISH: createIcon(IconStyles.SOLID, 'shrimp'),
  STEAK: createIcon(IconStyles.SOLID, 'utensils'),
  STEAKHOUSE: createIcon(IconStyles.SOLID, 'utensils'),
  SUSHI: createIcon(IconStyles.SOLID, 'sushi'),
  THAI: createIcon(IconStyles.SOLID, 'pepper-hot'),
  TURKISH: createIcon(IconStyles.SOLID, 'shish-kebab'),
  VIETNAMESE: createIcon(IconStyles.SOLID, 'bowl-hot'),

  // Dietary Restrictions
  NO_RESTRICTIONS: createIcon(IconStyles.SOLID, 'check-circle'),
  VEGETARIAN: createIcon(IconStyles.SOLID, 'leaf'),
  VEGAN: createIcon(IconStyles.SOLID, 'seedling'),
  GLUTEN_FREE: createIcon(IconStyles.SOLID, 'circle-gf'),
  HALAL: createIcon(IconStyles.SOLID, 'star-and-crescent'),
  KOSHER: createIcon(IconStyles.SOLID, 'star-of-david'),

  // Beverages
  WINE: createIcon(IconStyles.SOLID, 'wine-glass'),
  COCKTAILS: createIcon(IconStyles.SOLID, 'cocktail'),
  BEER: createIcon(IconStyles.SOLID, 'beer'),
  COFFEE_SERVICE: createIcon(IconStyles.SOLID, 'coffee'),

  // Amenities
  OUTDOOR_SEATING: createIcon(IconStyles.SOLID, 'table-picnic'),
  RESERVATIONS: createIcon(IconStyles.SOLID, 'calendar'),
  LIVE_MUSIC: createIcon(IconStyles.SOLID, 'music'),
  GROUP_DINING: createIcon(IconStyles.SOLID, 'people-group'),
  FAMILY_FRIENDLY: createIcon(IconStyles.SOLID, 'family-pants'),
  DOG_FRIENDLY: createIcon(IconStyles.SOLID, 'dog-leashed'),
  SPORTS: createIcon(IconStyles.SOLID, 'tv'),
  TAKEOUT: createIcon(IconStyles.SOLID, 'shopping-bag'),
  DELIVERY: createIcon(IconStyles.SOLID, 'truck'),
  WIFI: createIcon(IconStyles.SOLID, 'wifi'),
  PARKING: createIcon(IconStyles.SOLID, 'parking'),

  // Accessibility
  WHEELCHAIR: createIcon(IconStyles.SOLID, 'wheelchair-move'),

  // Tab Navigation
  DISCOVER: createIcon(IconStyles.SOLID, 'compass'),
  FAVORITES: createIcon(IconStyles.REGULAR, 'heart'),
  PROFILE: createIcon(IconStyles.SOLID, 'user')
} as const

export default AppIcons